dependencies:
  #- Get from github repository <organization/repo>@<version>
  - OpenZeppelin/openzeppelin-contracts@4.3.3
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.3"
networks:
  default: development
  development:
    verify: False
  rinkeby:
    verify: True
  mainnet-fork-dev:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
dotenv: .env
